import numpy as np
import matplotlib.pyplot as plt
from numba import jit
import matplotlib.animation as animation

def empty_grids(size):
    #+2 for boundary
    U = np.zeros((size, size))
    V = np.zeros((size, size))
    return U, V

def add_noise(grid, scale=0.01):
    """
    Add gaussian noise to the provided grid, scale controls the standard deviation of the noise.
    """
    noise = np.random.normal(0, scale, grid.shape)
    return grid + noise

def initialize_grids(size, type='assignment'):
    """
    Set up initial conditions.
    """
    size = size+2 # account for boundary
    U,V = empty_grids(size)
    if type == 'assignment':
        U+=0.5
        left_of_center = int(0.5*size-5)
        right_of_center = int(0.5*size+5)
        V[left_of_center:right_of_center, left_of_center:right_of_center] = 0.25
    elif type == 'set+noise':
        U+=0.5
        left_of_center = int(0.5*size-5)
        right_of_center = int(0.5*size+5)
        V[left_of_center:right_of_center, left_of_center:right_of_center] = 0.25
        U = add_noise(U, scale=0.1)
        V = add_noise(V, scale=0.1)
    return U, V

@jit(nopython=True)
def laplacian(grid):
    return (grid[2:, 1:-1] + grid[:-2, 1:-1] + grid[1:-1, 2:] + grid[1:-1, :-2] - 4*grid[1:-1, 1:-1])

@jit(nopython=True)
def forward_euler(U,V,params):
    """
    Perform one step of the forward euler method for the gray scott system
    """
    #unpack params
    f, k, Du, Dv, dt = params

    new_U = np.zeros_like(U)
    new_V = np.zeros_like(V)

    new_U[1:-1, 1:-1] = U[1:-1, 1:-1] + (Du*laplacian(U) - U[1:-1, 1:-1]*V[1:-1, 1:-1]**2 + f*(1-U[1:-1, 1:-1]))*dt
    new_V[1:-1, 1:-1] = V[1:-1, 1:-1] + (Dv*laplacian(V) + U[1:-1, 1:-1]*V[1:-1, 1:-1]**2 - (f+k)*V[1:-1, 1:-1])*dt

    return new_U, new_V

@jit(nopython=True)
def simulate(U, V, steps, params=None):
    """Run the simulation for given amount of steps. Return the entire history for animation"""
    history = np.zeros((steps, U.shape[0], U.shape[1], 2))
    if params is None:
        # params= (f, k, Du, Dv, dt)
        params = (0.0050, 0.0610, 0.16, 0.08, 1)
    for i in range(steps):
        U, V = forward_euler(U, V, params)
        history[i, :, :, 0] = U
        history[i, :, :, 1] = V
    return history

def plot(U, V):
    """
    Deprecated. USe animate() or animations. This function simply plots a single frame
    """
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.title('U concentration')
    plt.imshow(U, cmap='viridis',vmin=0, vmax=1)
    plt.colorbar()
    
    plt.subplot(1, 2, 2)
    plt.title('V concentration')
    plt.imshow(V, cmap='viridis',vmin=0, vmax=1)
    plt.colorbar()
    
    plt.tight_layout()
    plt.show()

def animate(source='sim_results/DR_sim_data.npy',save_path=None):
    """
    Animate the results generated by run_simulation. Save to MP4 if save_path is provided.
    """
    print("animating...")
    # only animate every 100 steps to save memory and speed up animation
    history = np.load(source)
    fig, axes = plt.subplots(1,2, figsize=(12, 5))
    
    im_u = axes[0].imshow(history[0, :, :, 0], cmap='Blues', vmin=0, vmax=1)
    im_v = axes[1].imshow(history[0, :, :, 1], cmap='Reds', vmin=0, vmax=1)

    axes[0].set_title("U Component")
    axes[1].set_title("V Component")

    def animate_frame(i):
        im_u.set_array(history[i, :, :, 0])
        im_v.set_array(history[i, :, :, 1])
        # Return both screens
        return [im_u, im_v]

    frame_indices = np.linspace(0, history.shape[0] - 1, 700, dtype=int)

    ani = animation.FuncAnimation(fig,animate_frame,frames=frame_indices,interval=50,blit=True)
    if save_path:
        ani.save(save_path, writer='ffmpeg', fps=20)
    plt.show()

def run_GS_simulation(F=0.035, k=0.065, Du=0.16, Dv=0.05, dt=1, filepath='sim_results/DR_sim_data.npy', initial_condition='set+noise'):
    """
    Run the Gray-Scott reaction-diffusion simulation with specified parameters and save results.
    """
    print("Initializing grids...")
    U, V = initialize_grids(size=100, type=initial_condition)
    print("Starting simulation...")
    params = (F, k, Du, Dv, dt)
    history = simulate(U, V, steps=5000, params=params)
    np.save(filepath, np.array(history))
    print("Simulation complete.")

# vvv Example usage vvv

run_GS_simulation(
    F=0.035, 
    k=0.065, 
    Du=0.16, 
    Dv=0.05, 
    dt=1, 
    filepath='sim_results/DR_sim_data.npy', 
    initial_condition='set+noise' # options: 'assignment' or 'set+noise'
)
animate(source='sim_results/DR_sim_data.npy', save_path='sim_results/DR_simulation.mp4')

# --------------------------------


# making figures

# run_GS_simulation(
#     F=0.035, 
#     k=0.06, 
#     Du=0.16, 
#     Dv=0.05, 
#     dt=1, 
#     filepath='sim_results/DR_sim_data.npy', 
#     initial_condition='set+noise' # options: 'assignment' or 'set+noise'
# )

# history = np.load('sim_results/DR_sim_data.npy')
# V = history[-1, :, :, 1]
# plt.imshow(V, cmap='viridis', vmin=0, vmax=1)
# plt.title('Final V concentration\n(F=0.035, k=0.06, Du=0.16, Dv=0.05, dt=1)')
# plt.show()

# special cases
# default
# params = (0.035, 0.06, 0.16, 0.08, 1)
# cool cell splitting behaviour
# params = (0.035, 0.065, 0.16, 0.05, 1) # f, k, Du, Dv, dt
# angled maze-like patterns
# params = (0.055, 0.062, 0.16, 0.05, 1) # f, k, Du, Dv, dt
# curvy maze-like patterns
# params = (0.029, 0.057, 0.16, 0.05, 1) # f, k, Du, Dv, dt